//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bildirimler
    {
        public int BildirimID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string Baslik { get; set; }
        public string Mesaj { get; set; }
        public string BildirimTuru { get; set; }
        public string OnemSeviyesi { get; set; }
        public bool OkunduMu { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
        public Nullable<System.DateTime> OkunmaTarihi { get; set; }
        public string ReferansTuru { get; set; }
        public Nullable<int> ReferansID { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
