//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depolar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Depolar()
        {
            this.MalKabulDetaylari = new HashSet<MalKabulDetaylari>();
            this.SevkiyatDetaylari = new HashSet<SevkiyatDetaylari>();
            this.StokHareketleri = new HashSet<StokHareketleri>();
            this.Stoklar = new HashSet<Stoklar>();
            this.UretimMalzemeTuketimleri = new HashSet<UretimMalzemeTuketimleri>();
            this.UretimMamulGirisleri = new HashSet<UretimMamulGirisleri>();
        }
    
        public int DepoID { get; set; }
        public int DepoKategoriID { get; set; }
        public string DepoKodu { get; set; }
        public string DepoAdi { get; set; }
        public Nullable<decimal> Kapasite { get; set; }
        public string Aciklama { get; set; }
        public bool AktifMi { get; set; }
    
        public virtual DepoKategorileri DepoKategorileri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MalKabulDetaylari> MalKabulDetaylari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SevkiyatDetaylari> SevkiyatDetaylari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StokHareketleri> StokHareketleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stoklar> Stoklar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimMalzemeTuketimleri> UretimMalzemeTuketimleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimMamulGirisleri> UretimMamulGirisleri { get; set; }
    }
}
