//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenelGiderler
    {
        public int GiderID { get; set; }
        public System.DateTime GiderTarihi { get; set; }
        public string GiderTuru { get; set; }
        public string BelgeNo { get; set; }
        public decimal Tutar { get; set; }
        public string ParaBirimi { get; set; }
        public string Aciklama { get; set; }
    }
}
