//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IhtiyacSatinAlmaBaglantilari
    {
        public int BaglantiID { get; set; }
        public int IhtiyacTalepDetayID { get; set; }
        public int SatinAlmaDetayID { get; set; }
        public decimal AktarilanMiktar { get; set; }
        public string Aciklama { get; set; }
    
        public virtual IhtiyacTalepDetaylari IhtiyacTalepDetaylari { get; set; }
        public virtual SatinAlmaDetaylari SatinAlmaDetaylari { get; set; }
    }
}
