//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IhtiyacTalepDetaylari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IhtiyacTalepDetaylari()
        {
            this.IhtiyacSatinAlmaBaglantilari = new HashSet<IhtiyacSatinAlmaBaglantilari>();
        }
    
        public int IhtiyacTalepDetayID { get; set; }
        public int IhtiyacTalepID { get; set; }
        public int UrunID { get; set; }
        public Nullable<int> UrunCesitID { get; set; }
        public decimal GerekliMiktar { get; set; }
        public decimal TalepMiktari { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IhtiyacSatinAlmaBaglantilari> IhtiyacSatinAlmaBaglantilari { get; set; }
        public virtual IhtiyacTalepleri IhtiyacTalepleri { get; set; }
        public virtual UrunCesitleri UrunCesitleri { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
