//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IhtiyacTalepleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IhtiyacTalepleri()
        {
            this.IhtiyacTalepDetaylari = new HashSet<IhtiyacTalepDetaylari>();
        }
    
        public int IhtiyacTalepID { get; set; }
        public string TalepNo { get; set; }
        public Nullable<int> UretimEmriID { get; set; }
        public System.DateTime TalepTarihi { get; set; }
        public Nullable<System.DateTime> IhtiyacTarihi { get; set; }
        public string Oncelik { get; set; }
        public string Durum { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IhtiyacTalepDetaylari> IhtiyacTalepDetaylari { get; set; }
        public virtual UretimEmirleri UretimEmirleri { get; set; }
    }
}
