//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IslemKayitlari
    {
        public int IslemKayitID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string IslemTuru { get; set; }
        public string TabloAdi { get; set; }
        public Nullable<int> KayitID { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime IslemTarihi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
