//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MalKabulleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MalKabulleri()
        {
            this.MalKabulDetaylari = new HashSet<MalKabulDetaylari>();
        }
    
        public int MalKabulID { get; set; }
        public string MalKabulNo { get; set; }
        public int SatinAlmaSiparisID { get; set; }
        public int TedarikciID { get; set; }
        public System.DateTime KabulTarihi { get; set; }
        public string IrsaliyeNo { get; set; }
        public string Durum { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MalKabulDetaylari> MalKabulDetaylari { get; set; }
        public virtual SatinAlmaSiparisleri SatinAlmaSiparisleri { get; set; }
        public virtual Tedarikciler Tedarikciler { get; set; }
    }
}
