//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MalKabulDetaylari
    {
        public int MalKabulDetayID { get; set; }
        public int MalKabulID { get; set; }
        public int SatinAlmaDetayID { get; set; }
        public int UrunID { get; set; }
        public Nullable<int> UrunCesitID { get; set; }
        public int DepoID { get; set; }
        public decimal GelenMiktar { get; set; }
        public decimal KabulEdilenMiktar { get; set; }
        public decimal ReddedilenMiktar { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Depolar Depolar { get; set; }
        public virtual MalKabulleri MalKabulleri { get; set; }
        public virtual SatinAlmaDetaylari SatinAlmaDetaylari { get; set; }
        public virtual UrunCesitleri UrunCesitleri { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
