//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriAlacaklari
    {
        public int AlacakID { get; set; }
        public int MusteriID { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public string BelgeNo { get; set; }
        public System.DateTime AlacakTarihi { get; set; }
        public Nullable<System.DateTime> VadeTarihi { get; set; }
        public decimal Tutar { get; set; }
        public string ParaBirimi { get; set; }
        public string Durum { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        public virtual Siparisler Siparisler { get; set; }
    }
}
