//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receteler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receteler()
        {
            this.ReceteDetaylari = new HashSet<ReceteDetaylari>();
            this.UretimEmirleri = new HashSet<UretimEmirleri>();
        }
    
        public int ReceteID { get; set; }
        public int UrunID { get; set; }
        public Nullable<int> UrunCesitID { get; set; }
        public string ReceteKodu { get; set; }
        public int VersiyonNo { get; set; }
        public string Aciklama { get; set; }
        public bool AktifMi { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceteDetaylari> ReceteDetaylari { get; set; }
        public virtual UrunCesitleri UrunCesitleri { get; set; }
        public virtual Urunler Urunler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimEmirleri> UretimEmirleri { get; set; }
    }
}
