//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceteDetaylari
    {
        public int ReceteDetayID { get; set; }
        public int ReceteID { get; set; }
        public int MalzemeUrunID { get; set; }
        public Nullable<int> MalzemeUrunCesitID { get; set; }
        public decimal GerekliMiktar { get; set; }
        public decimal FireOrani { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Urunler Urunler { get; set; }
        public virtual UrunCesitleri UrunCesitleri { get; set; }
        public virtual Receteler Receteler { get; set; }
    }
}
