//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolYetkileri
    {
        public int RolYetkiID { get; set; }
        public int RolID { get; set; }
        public int YetkiID { get; set; }
        public System.DateTime AtanmaTarihi { get; set; }
    
        public virtual Roller Roller { get; set; }
        public virtual Yetkiler Yetkiler { get; set; }
    }
}
