//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinAlmaSiparisleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SatinAlmaSiparisleri()
        {
            this.MalKabulleri = new HashSet<MalKabulleri>();
            this.SatinAlmaDetaylari = new HashSet<SatinAlmaDetaylari>();
            this.TedarikciBorclari = new HashSet<TedarikciBorclari>();
        }
    
        public int SatinAlmaSiparisID { get; set; }
        public string SatinAlmaSiparisNo { get; set; }
        public int TedarikciID { get; set; }
        public System.DateTime SiparisTarihi { get; set; }
        public Nullable<System.DateTime> BeklenenTeslimTarihi { get; set; }
        public string Durum { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MalKabulleri> MalKabulleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatinAlmaDetaylari> SatinAlmaDetaylari { get; set; }
        public virtual Tedarikciler Tedarikciler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TedarikciBorclari> TedarikciBorclari { get; set; }
    }
}
