//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatinAlmaDetaylari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SatinAlmaDetaylari()
        {
            this.IhtiyacSatinAlmaBaglantilari = new HashSet<IhtiyacSatinAlmaBaglantilari>();
            this.MalKabulDetaylari = new HashSet<MalKabulDetaylari>();
        }
    
        public int SatinAlmaDetayID { get; set; }
        public int SatinAlmaSiparisID { get; set; }
        public int UrunID { get; set; }
        public Nullable<int> UrunCesitID { get; set; }
        public decimal SiparisMiktari { get; set; }
        public decimal TeslimAlinanMiktar { get; set; }
        public decimal BirimFiyat { get; set; }
        public decimal IskontoOrani { get; set; }
        public decimal KDVOrani { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IhtiyacSatinAlmaBaglantilari> IhtiyacSatinAlmaBaglantilari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MalKabulDetaylari> MalKabulDetaylari { get; set; }
        public virtual SatinAlmaSiparisleri SatinAlmaSiparisleri { get; set; }
        public virtual UrunCesitleri UrunCesitleri { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
