//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SevkiyatDetaylari
    {
        public int SevkiyatDetayID { get; set; }
        public int SevkiyatID { get; set; }
        public Nullable<int> SiparisDetayID { get; set; }
        public int UrunID { get; set; }
        public Nullable<int> UrunCesitID { get; set; }
        public int DepoID { get; set; }
        public decimal SevkMiktari { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Depolar Depolar { get; set; }
        public virtual Sevkiyatlar Sevkiyatlar { get; set; }
        public virtual SiparisDetaylari SiparisDetaylari { get; set; }
        public virtual UrunCesitleri UrunCesitleri { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
