//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sevkiyatlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sevkiyatlar()
        {
            this.SevkiyatDetaylari = new HashSet<SevkiyatDetaylari>();
        }
    
        public int SevkiyatID { get; set; }
        public string SevkiyatNo { get; set; }
        public int MusteriID { get; set; }
        public Nullable<int> SiparisID { get; set; }
        public System.DateTime SevkiyatTarihi { get; set; }
        public string IrsaliyeNo { get; set; }
        public string Durum { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SevkiyatDetaylari> SevkiyatDetaylari { get; set; }
        public virtual Siparisler Siparisler { get; set; }
    }
}
