//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TedarikciOdemeleri
    {
        public int OdemeID { get; set; }
        public int TedarikciID { get; set; }
        public Nullable<int> BorcID { get; set; }
        public System.DateTime OdemeTarihi { get; set; }
        public decimal Tutar { get; set; }
        public string ParaBirimi { get; set; }
        public string OdemeYontemi { get; set; }
        public string BelgeNo { get; set; }
        public string Aciklama { get; set; }
    
        public virtual TedarikciBorclari TedarikciBorclari { get; set; }
        public virtual Tedarikciler Tedarikciler { get; set; }
    }
}
