//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TedarikciUrunleri
    {
        public int TedarikciUrunID { get; set; }
        public int TedarikciID { get; set; }
        public int UrunID { get; set; }
        public Nullable<int> UrunCesitID { get; set; }
        public string TedarikciUrunKodu { get; set; }
        public Nullable<decimal> SonAlisFiyati { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<int> OrtalamaTeslimSuresiGun { get; set; }
        public bool TercihEdilenMi { get; set; }
        public bool AktifMi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Tedarikciler Tedarikciler { get; set; }
        public virtual UrunCesitleri UrunCesitleri { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
