//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tedarikciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tedarikciler()
        {
            this.MalKabulleri = new HashSet<MalKabulleri>();
            this.SatinAlmaSiparisleri = new HashSet<SatinAlmaSiparisleri>();
            this.TedarikciBorclari = new HashSet<TedarikciBorclari>();
            this.TedarikciOdemeleri = new HashSet<TedarikciOdemeleri>();
            this.TedarikciUrunleri = new HashSet<TedarikciUrunleri>();
        }
    
        public int TedarikciID { get; set; }
        public string CariKod { get; set; }
        public string FirmaAdi { get; set; }
        public string YetkiliAdi { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string VergiNo { get; set; }
        public string VergiDairesi { get; set; }
        public string Adres { get; set; }
        public bool AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MalKabulleri> MalKabulleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatinAlmaSiparisleri> SatinAlmaSiparisleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TedarikciBorclari> TedarikciBorclari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TedarikciOdemeleri> TedarikciOdemeleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TedarikciUrunleri> TedarikciUrunleri { get; set; }
    }
}
