//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TedarikciBorclari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TedarikciBorclari()
        {
            this.TedarikciOdemeleri = new HashSet<TedarikciOdemeleri>();
        }
    
        public int BorcID { get; set; }
        public int TedarikciID { get; set; }
        public Nullable<int> SatinAlmaSiparisID { get; set; }
        public string BelgeNo { get; set; }
        public System.DateTime BorcTarihi { get; set; }
        public Nullable<System.DateTime> VadeTarihi { get; set; }
        public decimal Tutar { get; set; }
        public string ParaBirimi { get; set; }
        public string Durum { get; set; }
        public string Aciklama { get; set; }
    
        public virtual SatinAlmaSiparisleri SatinAlmaSiparisleri { get; set; }
        public virtual Tedarikciler Tedarikciler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TedarikciOdemeleri> TedarikciOdemeleri { get; set; }
    }
}
