//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimAlanlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UretimAlanlari()
        {
            this.UretimAlaniSorumlulari = new HashSet<UretimAlaniSorumlulari>();
            this.UretimEmriOperasyonlari = new HashSet<UretimEmriOperasyonlari>();
            this.UretimEmirleri = new HashSet<UretimEmirleri>();
        }
    
        public int UretimAlaniID { get; set; }
        public string AlanKodu { get; set; }
        public string AlanAdi { get; set; }
        public string Aciklama { get; set; }
        public bool AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimAlaniSorumlulari> UretimAlaniSorumlulari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimEmriOperasyonlari> UretimEmriOperasyonlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimEmirleri> UretimEmirleri { get; set; }
    }
}
