//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimEmriOperasyonlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UretimEmriOperasyonlari()
        {
            this.UretimOperasyonKullanicilari = new HashSet<UretimOperasyonKullanicilari>();
        }
    
        public int UretimEmriOperasyonID { get; set; }
        public int UretimEmriID { get; set; }
        public int OperasyonID { get; set; }
        public Nullable<int> UretimAlaniID { get; set; }
        public int SiraNo { get; set; }
        public Nullable<System.DateTime> PlanlananBaslangic { get; set; }
        public Nullable<System.DateTime> PlanlananBitis { get; set; }
        public Nullable<System.DateTime> GercekBaslangic { get; set; }
        public Nullable<System.DateTime> GercekBitis { get; set; }
        public decimal TamamlananMiktar { get; set; }
        public string Durum { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Operasyonlar Operasyonlar { get; set; }
        public virtual UretimAlanlari UretimAlanlari { get; set; }
        public virtual UretimEmirleri UretimEmirleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimOperasyonKullanicilari> UretimOperasyonKullanicilari { get; set; }
    }
}
