//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimMaliyetleri
    {
        public int UretimMaliyetID { get; set; }
        public int UretimEmriID { get; set; }
        public decimal MalzemeMaliyeti { get; set; }
        public decimal IscilikMaliyeti { get; set; }
        public decimal GenelUretimGideri { get; set; }
        public decimal DigerMaliyet { get; set; }
        public System.DateTime HesaplamaTarihi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual UretimEmirleri UretimEmirleri { get; set; }
    }
}
