//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimEmirleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UretimEmirleri()
        {
            this.IhtiyacTalepleri = new HashSet<IhtiyacTalepleri>();
            this.UretimEmriOperasyonlari = new HashSet<UretimEmriOperasyonlari>();
            this.UretimMaliyetleri = new HashSet<UretimMaliyetleri>();
            this.UretimMalzemeTuketimleri = new HashSet<UretimMalzemeTuketimleri>();
            this.UretimMamulGirisleri = new HashSet<UretimMamulGirisleri>();
        }
    
        public int UretimEmriID { get; set; }
        public string UretimEmriNo { get; set; }
        public Nullable<int> SiparisDetayID { get; set; }
        public int UrunID { get; set; }
        public Nullable<int> UrunCesitID { get; set; }
        public Nullable<int> ReceteID { get; set; }
        public Nullable<int> UretimAlaniID { get; set; }
        public decimal PlanlananMiktar { get; set; }
        public decimal UretilenMiktar { get; set; }
        public Nullable<System.DateTime> PlanlananBaslangic { get; set; }
        public Nullable<System.DateTime> PlanlananBitis { get; set; }
        public Nullable<System.DateTime> GercekBaslangic { get; set; }
        public Nullable<System.DateTime> GercekBitis { get; set; }
        public string Durum { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime OlusturmaTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IhtiyacTalepleri> IhtiyacTalepleri { get; set; }
        public virtual Receteler Receteler { get; set; }
        public virtual SiparisDetaylari SiparisDetaylari { get; set; }
        public virtual UretimAlanlari UretimAlanlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimEmriOperasyonlari> UretimEmriOperasyonlari { get; set; }
        public virtual UrunCesitleri UrunCesitleri { get; set; }
        public virtual Urunler Urunler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimMaliyetleri> UretimMaliyetleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimMalzemeTuketimleri> UretimMalzemeTuketimleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimMamulGirisleri> UretimMamulGirisleri { get; set; }
    }
}
