//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimAlaniSorumlulari
    {
        public int UretimAlaniSorumluID { get; set; }
        public int UretimAlaniID { get; set; }
        public int KullaniciID { get; set; }
        public System.DateTime AtanmaTarihi { get; set; }
        public bool AktifMi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual UretimAlanlari UretimAlanlari { get; set; }
    }
}
