//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UretimMamulGirisleri
    {
        public int MamulGirisID { get; set; }
        public int UretimEmriID { get; set; }
        public int UrunID { get; set; }
        public Nullable<int> UrunCesitID { get; set; }
        public int DepoID { get; set; }
        public decimal GirisMiktari { get; set; }
        public System.DateTime GirisTarihi { get; set; }
        public string Aciklama { get; set; }
    
        public virtual Depolar Depolar { get; set; }
        public virtual UretimEmirleri UretimEmirleri { get; set; }
        public virtual UrunCesitleri UrunCesitleri { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
