//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunCesitleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UrunCesitleri()
        {
            this.IhtiyacTalepDetaylari = new HashSet<IhtiyacTalepDetaylari>();
            this.MalKabulDetaylari = new HashSet<MalKabulDetaylari>();
            this.ReceteDetaylari = new HashSet<ReceteDetaylari>();
            this.Receteler = new HashSet<Receteler>();
            this.SatinAlmaDetaylari = new HashSet<SatinAlmaDetaylari>();
            this.SevkiyatDetaylari = new HashSet<SevkiyatDetaylari>();
            this.SiparisDetaylari = new HashSet<SiparisDetaylari>();
            this.StokHareketleri = new HashSet<StokHareketleri>();
            this.Stoklar = new HashSet<Stoklar>();
            this.TedarikciUrunleri = new HashSet<TedarikciUrunleri>();
            this.UretimEmirleri = new HashSet<UretimEmirleri>();
            this.UretimMalzemeTuketimleri = new HashSet<UretimMalzemeTuketimleri>();
            this.UretimMamulGirisleri = new HashSet<UretimMamulGirisleri>();
        }
    
        public int UrunCesitID { get; set; }
        public int UrunID { get; set; }
        public string CesitAdi { get; set; }
        public string Kod { get; set; }
        public string Aciklama { get; set; }
        public bool AktifMi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IhtiyacTalepDetaylari> IhtiyacTalepDetaylari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MalKabulDetaylari> MalKabulDetaylari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceteDetaylari> ReceteDetaylari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receteler> Receteler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatinAlmaDetaylari> SatinAlmaDetaylari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SevkiyatDetaylari> SevkiyatDetaylari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetaylari> SiparisDetaylari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StokHareketleri> StokHareketleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stoklar> Stoklar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TedarikciUrunleri> TedarikciUrunleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimEmirleri> UretimEmirleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimMalzemeTuketimleri> UretimMalzemeTuketimleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UretimMamulGirisleri> UretimMamulGirisleri { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
