//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UretimERP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YarisKabinERPEntities : DbContext
    {
        public YarisKabinERPEntities()
            : base("name=YarisKabinERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bildirimler> Bildirimler { get; set; }
        public virtual DbSet<Birimler> Birimler { get; set; }
        public virtual DbSet<DepoKategorileri> DepoKategorileri { get; set; }
        public virtual DbSet<Depolar> Depolar { get; set; }
        public virtual DbSet<GenelGiderler> GenelGiderler { get; set; }
        public virtual DbSet<IhtiyacSatinAlmaBaglantilari> IhtiyacSatinAlmaBaglantilari { get; set; }
        public virtual DbSet<IhtiyacTalepDetaylari> IhtiyacTalepDetaylari { get; set; }
        public virtual DbSet<IhtiyacTalepleri> IhtiyacTalepleri { get; set; }
        public virtual DbSet<IslemKayitlari> IslemKayitlari { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<KullaniciRolleri> KullaniciRolleri { get; set; }
        public virtual DbSet<MalKabulDetaylari> MalKabulDetaylari { get; set; }
        public virtual DbSet<MalKabulleri> MalKabulleri { get; set; }
        public virtual DbSet<MusteriAlacaklari> MusteriAlacaklari { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<MusteriTahsilatlari> MusteriTahsilatlari { get; set; }
        public virtual DbSet<Operasyonlar> Operasyonlar { get; set; }
        public virtual DbSet<ReceteDetaylari> ReceteDetaylari { get; set; }
        public virtual DbSet<Receteler> Receteler { get; set; }
        public virtual DbSet<Roller> Roller { get; set; }
        public virtual DbSet<RolYetkileri> RolYetkileri { get; set; }
        public virtual DbSet<SatinAlmaDetaylari> SatinAlmaDetaylari { get; set; }
        public virtual DbSet<SatinAlmaSiparisleri> SatinAlmaSiparisleri { get; set; }
        public virtual DbSet<SevkiyatDetaylari> SevkiyatDetaylari { get; set; }
        public virtual DbSet<Sevkiyatlar> Sevkiyatlar { get; set; }
        public virtual DbSet<SiparisDetaylari> SiparisDetaylari { get; set; }
        public virtual DbSet<Siparisler> Siparisler { get; set; }
        public virtual DbSet<SistemAyarlari> SistemAyarlari { get; set; }
        public virtual DbSet<StokHareketleri> StokHareketleri { get; set; }
        public virtual DbSet<Stoklar> Stoklar { get; set; }
        public virtual DbSet<TedarikciBorclari> TedarikciBorclari { get; set; }
        public virtual DbSet<Tedarikciler> Tedarikciler { get; set; }
        public virtual DbSet<TedarikciOdemeleri> TedarikciOdemeleri { get; set; }
        public virtual DbSet<TedarikciUrunleri> TedarikciUrunleri { get; set; }
        public virtual DbSet<UretimAlaniSorumlulari> UretimAlaniSorumlulari { get; set; }
        public virtual DbSet<UretimAlanlari> UretimAlanlari { get; set; }
        public virtual DbSet<UretimEmirleri> UretimEmirleri { get; set; }
        public virtual DbSet<UretimEmriOperasyonlari> UretimEmriOperasyonlari { get; set; }
        public virtual DbSet<UretimMaliyetleri> UretimMaliyetleri { get; set; }
        public virtual DbSet<UretimMalzemeTuketimleri> UretimMalzemeTuketimleri { get; set; }
        public virtual DbSet<UretimMamulGirisleri> UretimMamulGirisleri { get; set; }
        public virtual DbSet<UretimOperasyonKullanicilari> UretimOperasyonKullanicilari { get; set; }
        public virtual DbSet<UrunCesitleri> UrunCesitleri { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<UrunTipleri> UrunTipleri { get; set; }
        public virtual DbSet<Yetkiler> Yetkiler { get; set; }
    }
}
